name = "clipaction-waitlist"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[pages]
build_output_dir = ".wrangler/tmp/pages"

[env.development]
vars = { ENVIRONMENT = "development" } 